### PR TITLE
translate in accordance with the original English version readme.md

### PR DESCRIPTION
**Pull request by libi**
translate in accordance with the original English version of readme.md and remove any advertising

### CODE REVIEW

**Comment by Supalosa** [comment]
Thank you, both. After libi's most recent change I am happy with this. (I also asked a Chinese-speaking friend to validate for me).

**Comment by Supalosa** [comment]
There is a dispute about the naming of the underlying project (Chrono Divide, 网页红警). The argument has been made that the latter is more searchable. However, I want to respect the origins of the actual underlying project, Chrono Divide, and ensure that the origins are not lost or confused.

Is it fair to put both names in the README-CN.md? For example, Chrono Divide (网页红警). I'm not sure if 网页红警 is a literal translation or a "brand name".

**Comment by Supalosa** [comment]
If we want to make this simpler, let's just remove the sentence about GPT in this PR.

**Comment by libi** [comment]
"网页红警" has been operated as a brand name by Ra2web on social networking sites in China. According to Chrono Divide's official translation, it should be "网页版红警2"。https://game.chronodivide.com/res/locale/zh-CN.json?v=0.56.0 。
"网页版红警2"  is more searchable  .

**Pull request closed without merging**
